# Loads default set of integrations. Do not remove.
default_config:

# HTTP configuration for reverse proxy support
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.25.0.0/16  # Docker network range
    - 127.0.0.1
    - ::1
  # Allow access from Tailscale domain
  server_host: 0.0.0.0

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
